# Generated by Django 3.1.2 on 2020-11-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('genre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.DeleteModel(
            name='Abc',
        ),
    ]
